services:
  nginx:
    container_name: laravel_nginx
    build:
      context: .
      dockerfile: ./docker-local/nginx/Dockerfile
    volumes:
      - ./docker-local/nginx/conf:/etc/nginx/conf.d
    ports:
      - '80:80'

  api:
    container_name: laravel_api
    build:
      context: .
      dockerfile: ./docker-local/php/Dockerfile
    volumes:
      - './api:/api'

  database:
    container_name: laravel_db
    image: mysql:8.0
    volumes:
      - laravel-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  laravel-data:
